In [1]:
import numpy as np

In [2]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [3]:
data + 1

array([0, 2, 4, 6, 8])

In [25]:
data * data

array([ 0,  1,  4,  9, 16])

In [27]:
data[2:]

array([2, 3, 4])

In [28]:
data > 2

array([False, False, False,  True,  True])

In [8]:
data.ndim

1

In [4]:
data.shape

(5,)

In [5]:
data.dtype

dtype('int32')

In [7]:
pylist = [[0, 1, 2], [3, 4, 5]]
np.array(pylist)

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
pytuple = (2, 3)
pytuple3d = (2, 3, 2)

In [12]:
np.zeros(pytuple)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(pytuple)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full(pytuple, 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [16]:
# 値に意味なし。場所取り
np.empty(pytuple3d)

array([[[6.98511998e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.00536071e-070]],

       [[1.76070175e-076, 1.00713967e-046],
        [6.58138630e-038, 1.93466498e+184],
        [1.27070299e-075, 1.38213715e-047]]])

In [22]:
pylist = [1.1, 2.5]
pylist = np.array(pylist)
pyliststr = ['1.1', '2.5']

In [21]:
pylist.astype(np.int32)

array([1, 2])

In [23]:
pyliststr = np.array(pyliststr, dtype=np.string_)
pyliststr.astype(float)

array([1.1, 2.5])

In [30]:
data2d = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
data2d[0]

array([1, 2, 3])

In [39]:
data2d[0, 1]

2

In [42]:
data2d[0, 1:]

array([2, 3])

In [43]:
data2d[0:, 1]

array([2, 5])

In [44]:
data2d[0:, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
data2d[:, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
data2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
np.sqrt(data2d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
np.exp(data2d)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [53]:
data2d2 = np.array([[3, 4, 5], [6, 1, 2]])

In [54]:
np.max(data2d)

6

In [56]:
np.maximum(data2d, data2d2)

array([[3, 4, 5],
       [6, 5, 6]])

In [59]:
data = np.arange(5)
data2 = np.array([3, 4, 5, 1, 2])
data2d = np.array([[3, 4, 5], [6, 1, 2]])
cond = data < data2
cond

array([ True,  True,  True, False, False])

In [62]:
np.where(cond, 'Yes', 'No')

array(['Yes', 'Yes', 'Yes', 'No', 'No'], dtype='<U3')

In [61]:
# trueならdata
np.where(cond, data, data2)

array([0, 1, 2, 1, 2])

In [84]:
data[cond]

array([0, 1, 2])

In [63]:
data.mean()

2.0

In [64]:
data.sum()

10

In [70]:
data2d.sum(axis=0)

array([5, 7, 9])

In [68]:
data2d.sum(axis=1)

array([ 6, 15])

In [79]:
data2d = np.array([[3, 4, 5], [6, 1, 2]])

In [80]:
data2d.sort()
data2d

array([[3, 4, 5],
       [1, 2, 6]])

In [82]:
data2d.sort(axis=0)
data2d

array([[1, 2, 5],
       [3, 4, 6]])

In [85]:
datastr = np.array(['a', 'b', 'c', 'b', 'B', 'c'])

In [87]:
np.unique(datastr)

array(['B', 'a', 'b', 'c'], dtype='<U1')

In [88]:
np.in1d(datastr, ['a', 'b', 'c'])

array([ True,  True,  True,  True, False,  True])

In [89]:
np.intersect1d(datastr, ['a', 'b', 'e'])

array(['a', 'b'], dtype='<U1')

In [90]:
np.save('savetest', data)

In [92]:
np.load('savetest.npy')

array([0, 1, 2, 3, 4])